/*
SELECT 
    AD, SOYAD, 
    MAAS "MAAŞ", 
    (MAAS*5/100) AS VERGİ, 
    SEMT AS "OTURDUĞU SEMT"
FROM PERSONEL
*/

/*
SELECT 
    AD, SOYAD, MAAS,
        (MAAS + MAAS*8/100) ZAMLI_MAAS
FROM PERSONEL
*/

/*
SELECT
    AD, SOYAD,
    GIRIS_TARIHI + 7 AS ORYANTASYON_GUNU,
    30 - IZIN_GUNU AS KALAN_IZIN_GUN_SAYISI
FROM PERSONEL

SELECT
    AD, SOYAD,
    GIRIS_TARIHI AS ORYANTASYON_GUNU
FROM PERSONEL
*/

/*
SELECT
    AD, SOYAD, SEMT, MAAS, PRIM,
    (MAAS + PRIM) AS HESABA_YATAN
    FROM PERSONEL
*/

/*
SELECT
    AD, SOYAD,
    AD || ' ' || SOYAD ADI_SOYADI,
    CONCAT(AD, SOYAD) ADSOYAD,
    MAAS || ' TL' MAASI 
FROM PERSONEL;
*/

/*
SELECT
    AD, SOYAD, PRIM, SEMT,
    'Prim: [' || PRIM || '] Semt: [' || SEMT || '] ' PRIM_SEMT
FROM PERSONEL
*/

/*
SELECT
    AD, SOYAD,
    ''|| AD ||'.'|| SOYAD ||'@dbhunter.net ' AS EMAIL,
    MAAS AS ESKI_MAAS,
    (MAAS*1.45) AS YENI_MAAS
FROM PERSONEL
*/

/*
SELECT
    DISTINCT ''||AD||' '||SOYAD||'' AS AD_SOYAD, IZIN_GUNU
FROM PERSONEL    

DESCRIBE PERSONEL
*/

/*
select *

from nls_database_parameters

where parameter = 'NLS_DATE_FORMAT';

SELECT
    *
FROM PERSONEL
WHERE TO_DATE('21-08-2010', 'DD-MM-YYYY') BETWEEN GIRIS_TARIHI AND CIKIS_TARIHI;
*/

/*
SELECT * FROM PERSONEL
WHERE PRIM IS NULL
*/

/*
SELECT
    *
FROM PERSONEL 
WHERE GIRIS_TARIHI = '20122011'
*/

/*
SELECT 
    AD,
    LOWER(AD) KUCUK_HARF,
    UPPER(AD) BUYUK_HARF,
    INITCAP(AD) ILK_HARF,
    CONCAT(AD, SOYAD) BIRLESTIR,
    SUBSTR(AD, 0, 3) SINIRLAMA,
    LENGTH(AD) UZUNLUK,
    LPAD(AD, 22, '+'),
    RPAD(AD, 22, '-'),
    REPLACE(AD, )
FROM PERSONEL  WHERE AD = 'HALİL İBRAHİM'
*/

/*
SELECT
    MAAS,
    ROUND(MAAS)
FROM PERSONEL    
*/

/*
SELECT CAST('100' AS INTEGER) AS CAST1
FROM DUAL;
*/

/*
SELECT AD, SOYAD, MAAS, PRIM,
    MAAS + COALESCE(PRIM, 0) AS HESABA_YATAN
FROM PERSONEL;    
*/

/*
SELECT 
    AD, SOYAD, UNVAN, MAAS,
        DECODE(
            UNVAN,
            'MUHENDIS', MAAS*0.05, 
            'UZMAN', MAAS*0.02, 
            MAAS*0.03
        ) KESINTI
FROM PERSONEL
*/

/*
SELECT
    COMPANY_NAME, CONTACT_NAME, CONTACT_TITLE,
    CASE
        WHEN LOWER(CONTACT_TITLE) LIKE '%admin%' THEN 'Ad.Position'
        WHEN LOWER(CONTACT_TITLE) LIKE '%manager%' THEN 'Man.Position'
        WHEN LOWER(CONTACT_TITLE) LIKE '%representative%' THEN 'Rep.Position'
        WHEN LOWER(CONTACT_TITLE) LIKE '%assistant%' THEN 'As.Position'
        ELSE 'Other Position'
    END position_type    
FROM CUSTOMERS   
*/

/*
SELECT
    AD, SOYAD, PRIM, INITCAP(UNVAN) UNVANX, TO_CHAR(GIRIS_TARIHI, 'DD MONTH YY') TARIH,
        DECODE(PRIM, NULL, 'NORMAL', 'TORPILLI') DURUM
FROM PERSONEL
WHERE INSTR(LOWER(UNVAN), 'd') > 0
*/

/*
SELECT
    AD, MIN(MAAS) MINIMUM_MAAS
FROM PERSONEL
GROUP BY AD
ORDER BY 2 DESC
*/

/*
SELECT
    KONUM_ID, COUNT(*) PERSONEL_SAYISI, SUM(MAAS) TOPLAM_MAAS, ROUND(AVG(MAAS), 2) ORTALAMA_MAAS
FROM PERSONEL
GROUP BY KONUM_ID
HAVING COUNT(*) > 10
*/

/*
SELECT
    SEMT, COUNT(*) PERSONEL_SAYISI
FROM PERSONEL    
GROUP BY SEMT
HAVING COUNT(*) > 5
*/

/*
SELECT
    SUPPLIER_ID, COUNT(*)
FROM PRODUCTS    
GROUP BY SUPPLIER_ID
HAVING COUNT(*) > 3
*/

/*
SELECT
    *
FROM BASKET_A
LEFT JOIN BASKET_B ON ID_B = ID_A;

SELECT
    *
FROM BASKET_B
LEFT JOIN BASKET_A ON ID_A = ID_B;
    
SELECT * FROM BASKET_A;
SELECT * FROM BASKET_B;
*/

/*
SELECT
    AD, SOYAD, MAAS, UNVAN, KONUM_ID
FROM PERSONEL
WHERE
    MAAS BETWEEN 1200 AND 2500
    AND KONUM_ID = 1
UNION
SELECT AD, SOYAD, MAAS, UNVAN, KONUM_ID
FROM PERSONEL
WHERE
    MAAS BETWEEN 2500 AND 5000
    AND KONUM_ID = 1
*/

/*
SELECT
    COUNTRY, COMPANY_NAME, COUNT(*) AS ORDER_COUNT
FROM CUSTOMERS C, ORDERS O
WHERE
    COUNTRY IN ('France', 'Germany')
    AND C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY COUNTRY, COMPANY_NAME, C.CUSTOMER_ID
UNION
SELECT COUNTRY, COMPANY_NAME, COUNT(*) AS ORDER_COUNT
FROM CUSTOMERS C, ORDERS O
WHERE COUNTRY = 'Germany'
    AND C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY COUNTRY, COMPANY_NAME, C.CUSTOMER_ID
ORDER BY 3
*/

/*
DECLARE
    v_country VARCHAR2(50);
BEGIN
    v_country := INITCAP('FRANCE');
    
    EXECUTE IMMEDIATE '
    SELECT COUNTRY, COMPANY_NAME, COUNT(*) AS ORDER_COUNT
    FROM CUSTOMERS C, ORDERS O
    WHERE
        COUNTRY IN (''' || v_country || ''', ''Germany'')
        AND C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY COUNTRY, COMPANY_NAME
    ORDER BY 3';
END;
*/

/*
SELECT 'Customer' as type_of_company, COMPANY_NAME FROM CUSTOMERS
UNION ALL
SELECT 'Shipper' as type_of_company, COMPANY_NAME FROM SHIPPERS
UNION ALL
SELECT 'Supplier' as type_of_company, COMPANY_NAME FROM SUPPLIERS
*/

/*
SELECT * FROM PRODUCTS P
INNER JOIN SUPPLIERS S ON S.SUPPLIER_ID = P.SUPPLIER_ID
*/
/*
SELECT
    S.COMPANY_NAME, S.*
FROM SUPPLIERS S, PRODUCTS P
WHERE P.SUPPLIER_ID = S.SUPPLIER_ID
    AND P.CATEGORY_ID = 2
INTERSECT
SELECT 
    S.COMPANY_NAME, S.*
FROM SUPPLIERS S, PRODUCTS P
WHERE P.SUPPLIER_ID = S.SUPPLIER_ID
    AND P.CATEGORY_ID = 5
*/    

/*
SELECT * FROM PERSONEL
WHERE MAAS < ANY (SELECT MAAS FROM PERSONEL WHERE UNVAN = 'UZMAN');

SELECT * FROM PERSONEL
WHERE EXISTS (SELECT MAAS FROM PERSONEL WHERE UNVAN = 'UZMAN');
*/

/*
SELECT * FROM PERSONEL
WHERE MAAS < ALL (SELECT MAAS FROM PERSONEL WHERE PERSONEL_ID = 5037);
*/

/*
INSERT INTO KONUM (KONUM_ID, KONUM_ADI, IL_KODU)
VALUES (10, 'Ankara-Yenimahalle', 6);

SELECT * FROM KONUM

DELETE FROM KONUM WHERE KONUM_ID = 10

INSERT INTO KONUM
VALUES (1, 'Bursa - Nilüfer', 16)

INSERT INTO KONUM
VALUES (99, 'Bursa - Konak Mahallesi', 166)

DELETE FROM KONUM WHERE KONUM_ID = 1 AND IL_KODU = 16

UPDATE KONUM
SET KONUM_ADI = 'KONAK MAHALLESI'
WHERE IL_KODU = 166
*/

/*
INSERT INTO COLORS VALUES ('Pink');

INSERT INTO COLORS VALUES ('Navy');

INSERT INTO COLORS VALUES ('Indigo');

UPDATE COLORS SET COLOUR = 'Light Blue' WHERE COLOR = 'Blue';

SELECT * FROM COLORS;

commit;
*/

--COMMIT AND ROLLBACK--

/*
----SELECTS----
SELECT SUM(NET_PRICE) FROM PRODUCT;
SELECT * FROM PRODUCT;
SELECT * FROM PRODUCT_SEGMENT;
----SELECTS----

UPDATE PRODUCT_SEGMENT SET DISCOUNT = DISCOUNT + 0.08;

UPDATE PRODUCT P SET NET_PRICE = PRICE - PRICE * (SELECT S.DISCOUNT FROM PRODUCT_SEGMENT S WHERE S.ID = P.SEGMENT_ID);

savepoint ALL_SEGMENT;

UPDATE PRODUCT_SEGMENT SET DISCOUNT = DISCOUNT + 0.15 WHERE SEGMENT LIKE 'Luxury%';

UPDATE PRODUCT P SET NET_PRICE = PRICE - PRICE * ( SELECT S.DISCOUNT FROM PRODUCT_SEGMENT S WHERE S.ID = P.SEGMENT_ID)
WHERE P.SEGMENT_ID IN
    (SELECT PS.ID FROM PRODUCT_SEGMENT PS WHERE PS.SEGMENT LIKE '%LUXURY%');
    
savepoint LUXURY_SEGMENT;

UPDATE PRODUCT_SEGMENT SET DISCOUNT = DISCOUNT + 0.05 WHERE SEGMENT LIKE 'Mass';

UPDATE PRODUCT P SET NET_PRICE = PRICE - PRICE * ( SELECT DISCOUNT FROM PRODUCT_SEGMENT S WHERE S.ID = P.SEGMENT_ID )
WHERE P.SEGMENT_ID IN ( SELECT ID FROM PRODUCT_SEGMENT WHERE SEGMENT LIKE 'Mass' );

savepoint LUXURY_SEGMENT2;

rollback to LUXURY_SEGMENT;
rollback to ALL_SEGMENT;
*/

/*
SELECT * FROM MUDURLUK WHERE IL_ADI = 'BURSA';

DELETE FROM MUDURLUK WHERE MUDURLUK_KODU = 8789;
*/

/*
SELECT * FROM PERSONEL WHERE UNVAN = 'TEKNİKER' for update;


DROP TABLE EGITIM2.CEZA_BILGI

SELECT * FROM CEZA_BILGI;

CREATE TABLE EGITIM2.CEZA_BILGI
(
    PERSONEL_ID NUMBER,
    CEZA_ACIKLAMA VARCHAR2(100 BYTE),
    BASLANGIC_TARIHI DATE DEFAULT SYSDATE,
    BITIS_TARIHI DATE
)

CREATE TABLE DERSLER(
    DERS_ID NUMBER,
    DERS_ISMI VARCHAR2(50),
    DERS_ACIKLAMASI VARCHAR2(250),
    ILK_DERS_TARIHI DATE,
    DERS_KAPASITESI INTEGER DEFAULT 20,
    DERS_HOCASI VARCHAR2(70) DEFAULT 'Henuz atama yapilmamis'
)
*/

/*
CREATE VIEW VW_KONUM AS
SELECT 
    AD, SOYAD, SEMT, KONUM_ADI
FROM PERSONEL PS, KONUM KN
WHERE PS.KONUM_ID = KN.KONUM_ID

SELECT * FROM VW_KONUM
*/

/*

CREATE OR REPLACE VIEW VW_YONETICILER AS
SELECT
    YN.YONETICI_ID, PS.AD, PS.SOYAD,
    PS.UNVAN, PK.KONUM_ADI,
    (PS.MAAS + NVL(PS.PRIM, 0)) GELIR
FROM YONETICI YN, PERSONEL PS, KONUM PK
WHERE PS.PERSONEL_ID = YN.PERSONEL_ID
AND PS.KONUM_ID = PK.KONUM_ID;

SELECT * FROM VW_YONETICILER
*/

/*
SELECT * FROM VW_CUST_ORDER_INFO;
SELECT * FROM CUSTOMERS;

CREATE OR REPLACE VIEW VW_CUST_ORDER_INFO AS
SELECT
     C.COMPANY_NAME, C.CONTACT_NAME,
     O.CUSTOMER_ID, O.ORDER_DATE, O.ORDER_ID,
     O.FREIGHT, O.SHIP_CITY
FROM CUSTOMERS C, ORDERS O
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID;



SELECT * FROM VW_CUST_ORDER_INFO;

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;


SELECT * FROM VW_CUST_ORDER_INFO;

CREATE OR REPLACE VIEW CUST_ORDER_PROD_INFO AS
SELECT
    CO.CUSTOMER_ID, CO.COMPANY_NAME,
    CO.ORDER_DATE, CO.FREIGHT, CO.SHIP_CITY,
    P.PRODUCT_NAME, P.UNIT_PRICE
FROM
    VW_CUST_ORDER_INFO CO,
    ORDER_DETAILS OD, PRODUCTS P
WHERE 1=1
    AND CO.ORDER_ID = OD.ORDER_ID
    AND P.PRODUCT_ID = OD.PRODUCT_ID;

SELECT * FROM cust_order_prod_ınfo;
*/

/*
CREATE OR REPLACE VIEW VW_PRODUCT_GRAND_LUX AS
SELECT ID, NAME, PRICE, SEGMENT_ID FROM PRODUCT
WHERE SEGMENT_ID = 1;

CREATE VIEW VW_PRODUCT_GRAND_LUX AS
SELECT ID, NAME, PRICE FROM PRODUCT
WHERE SEGMENT_ID = 1;

SELECT * FROM PRODUCT WHERE SEGMENT_ID = 1;
SELECT * FROM PRODUCT_SEGMENT;
SELECT * FROM VW_PRODUCT_GRAND_LUX;

UPDATE VW_PRODUCT_GRAND_LUX
SET PRICE = PRICE * 1.4;

DELETE FROM VW_PRODUCT_GRAND_LUX
WHERE ID = 11;

SELECT * FROM VW_PRODUCT_GRAND_LUX;

INSERT INTO VW_PRODUCT_GRAND_LUX(ID, NAME, PRICE, SEGMENT_ID)
VALUES(11, 'Wardrobe', 2000, 1);
*/

/*

--CREATE VIEW VW_UZMAN AS
SELECT * FROM PERSONEL WHERE UNVAN = 'UZMAN';

CREATE OR REPLACE VIEW VW_UZMAN AS
SELECT * FROM PERSONEL WHERE UNVAN = 'UZMAN'
--with read only;
WITH CHECK OPTION;

UPDATE VW_UZMAN SET KONUM_ID = 5 WHERE PRIM > 0;

UPDATE VW_UZMAN SET UNVAN = 'ŞEF';
UPDATE VW_UZMAN SET KONUM_ID = 19;
*/

/*
CREATE INDEX PERSONEL_NI1 ON PERSONEL(PERSONEL_ID);

SELECT * FROM PERSONEL WHERE AD = 'SERKAN';

SELECT * FROM PERSONEL WHERE PERSONEL_ID = 5001;
*/
--KOLON EKLEME
/*
SELECT * FROM PERSONEL;

ALTER TABLE PERSONEL ADD (EMAIL VARCHAR2(150));

SELECT
    TRANSLATE(LOWER(REPLACE(AD, ' ','')), 'ıöüçşğ', 'ioutcsg') ||'.'||
    TRANSLATE(LOWER(REPLACE(SOYAD, ' ','')), 'ıöüğçşğ', 'ioucsg') || '@dbhunter.net' as email
FROM PERSONEL;

UPDATE PERSONEL SET EMAIL =
    TRANSLATE(LOWER(REPLACE(AD, ' ','')), 'ıöüçşğ', 'ioucsg') ||'.'||
    TRANSLATE(LOWER(REPLACE(SOYAD, ' ','')),'ıöüğçşğ', 'ioucsg') || '@dbhunter.net';
    
CREATE UNIQUE INDEX uq_personel_email on personel(email);

UPDATE PERSONEL SET EMAIL = 'servet.turan2@dbhunter.net' WHERE PERSONEL_ID = 5084;

SELECT EMAIL, COUNT(*) FROM PERSONEL
GROUP BY EMAIL
HAVING COUNT(*) > 1;

SELECT * FROM PERSONEL
WHERE AD = 'SERVET';

SELECT * FROM PERSONEL WHERE EMAIL = 'servet.turan@dbhunter.net';
*/

/*
EXPLAIN PLAN FOR
SELECT
    C.CUSTOMER_ID, C.COMPANY_NAME, C.CONTACT_NAME,
    O.ORDER_ID, O.ORDER_DATE, O.FREIGHT, O.SHIP_CITY
FROM CUSTOMERS C, ORDERS O
WHERE C.CUSTOMER_ID = O.CUSTOMER_ID;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());

EXPLAIN PLAN FOR
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID = 'PARIS';

CREATE INDEX PERSONEL_NI2 ON PERSONEL(UPPER(AD));

EXPLAIN PLAN FOR
SELECT * FROM PERSONEL WHERE UPPER(AD) = 'SERKAN';

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());

--INDEX OLUSTURMA

CREATE INDEX IX_PERSONEL_ID ON PERSONEL(PERSONEL_ID);

CREATE INDEX IX_MUDURLUK_IL ON MUDURLUK(IL_ADI);
CREATE INDEX IX_MUDURLUK_IL_LOWER ON MUDURLUK(LOWER(IL_ADI));

EXPLAIN PLAN FOR
SELECT IL_ADI FROM MUDURLUK;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());

EXPLAIN PLAN FOR
SELECT * FROM PERSONEL WHERE PERSONEL_ID = 5070;

EXPLAIN PLAN FOR
SELECT * FROM MUDURLUK WHERE LOWER(IL_ADI) = 'ANKARA';

CREATE INDEX UQ_EMP_CITY_POSTAL ON EMPLOYEES(CITY, POSTAL_CODE);

EXPLAIN PLAN FOR
SELECT * FROM EMPLOYEES WHERE CITY = 'TACOMA' AND POSTAL_CODE = 98401;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY());
*/

/*
SELECT * FROM KONUM;

CREATE SEQUENCE SQ_KONUM INCREMENT BY 1
START WITH 10;

INSERT INTO KONUM(KONUM_ID, KONUM_ADI, IL_KODU)
VALUES(SQ_KONUM.NEXTVAL, 'Mecidiyeköy', 21);

DELETE FROM KONUM WHERE KONUM_ADI = 'Bursa', 1666;

CREATE SEQUENCE SQ_GERIYE_DOGRU
    INCREMENT BY -2
    START WITH 100
    MAXVALUE 100;

SELECT SQ_GERIYE_DOGRU.NEXTVAL FROM DUAL;
*/

/*
ALTER TABLE COLORS ADD(COLOR_ID INTEGER);

CREATE SEQUENCE SQ_COLORS
START WITH 1
INCREMENT BY 1;

UPDATE COLORS SET COLOR_ID = SQ_COLORS.NEXTVAL;

SELECT * FROM COLORS;
*/

/*
CREATE SYNONYM SUBE FOR MUDURLUK_SUBE;

DROP SYNONYM SUBE;

SELECT * FROM MUDURLUK_SUBE;

CREATE PUBLIC SYNONYM SUBE FOR 

*/

/*
SELECT CURRENT_DATE, CURRENT_TIMESTAMP, LOCALTIMESTAMP FROM DUAL;

ALTER SESSION SET TIME_ZONE = '-3.00';

SELECT DBTIMEZONE, SESSIONTIMEZONE FROM DUAL;
*/
--BUYUK VERI KUMELERI
/*
INSERT INTO CEZA_BILGI
SELECT 
    PERSONEL_ID, 
    'UZMANLAR CALISMIYOR',
    SYSDATE, SYSDATE+10
FROM PERSONEL WHERE UNVAN = 'UZMAN';

SELECT * FROM IZIN_TURLERI;
SELECT * FROM PERSONEL_IZINLERI;

INSERT INTO PERSONEL_IZINLERI(
    PERSONEL_ID,
    IZIN_TURU,
    IZIN_BAS_TARIHI,
    IZIN_BIT_TARIHI,
    IZIN_BAS_SAATI,
    IZIN_BIT_SAATI
)
SELECT 
    PERSONEL_ID, 
    1, 
    SYSDATE + 1, 
    SYSDATE + 3, 
    NULL, 
    NULL 
FROM PERSONEL WHERE UNVAN = 'MÜDÜR';

CREATE TABLE PERSONEL_BORDRO
(
    PERSONEL_ID NUMBER,
    MAAS NUMBER,
    PRIM NUMBER
);

INSERT INTO PERSONEL_BORDRO
SELECT PERSONEL_ID, MAAS, PRIM
FROM PERSONEL;

CREATE TABLE UK_EMP_ORDERS AS
SELECT
    E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME,
    O.ORDER_DATE, O.FREIGHT, O.SHIP_CITY
FROM EMPLOYEES E, ORDERS O
WHERE E.COUNTRY = 'UK' AND
E.EMPLOYEE_ID = O.EMPLOYEE_ID;

SELECT * FROM UK_EMP_ORDERS WHERE EMPLOYEE_ID = 5;

INSERT INTO BASKET_C(ID_C, FRUIT_C)
SELECT ROWNUM, FRUIT FROM
(
    SELECT FRUIT_A AS FRUIT FROM BASKET_A
    UNION
    SELECT FRUIT_B FROM BASKET_B
);

SELECT * FROM BASKET_C;

CREATE TABLE PERSONEL_SICIL AS SELECT PERSONEL_ID, AD, SOYAD FROM PERSONEL WHERE 1=0;

CREATE TABLE PERSONEL_MAAS AS SELECT PERSONEL_ID, MAAS, PRIM FROM PERSONEL WHERE 1 = 0;

DROP TABLE PERSONEL_SICIL;

SELECT * FROM PERSONEL_SICIL;
SELECT * FROM PERSONEL_MAAS;

SELECT * FROM PERSONEL WHERE UNVAN = 'UZMAN';

--COKLU INSERT SARTSIZ
INSERT ALL
    INTO PERSONEL_SICIL VALUES(PERSONEL_ID, AD, SOYAD)
    INTO PERSONEL_MAAS VALUES(PERSONEL_ID, MAAS, PRIM)
SELECT AD, SOYAD, PERSONEL_ID, MAAS, PRIM        
FROM PERSONEL
WHERE UNVAN = 'UZMAN';

SELECT
    PS.PERSONEL_ID, PS.AD, PS.SOYAD, PM.MAAS, PM.PRIM
FROM PERSONEL_SICIL PS, PERSONEL_MAAS PM  
WHERE PS.PERSONEL_ID = PM.PERSONEL_ID;

CREATE TABLE PERSONEL_UZMAN AS SELECT PERSONEL_ID, AD, SOYAD, MAAS, UNVAN FROM PERSONEL WHERE 1 = 0;
CREATE TABLE PERSONEL_YONETICI AS SELECT PERSONEL_ID, AD, SOYAD, MAAS, UNVAN FROM PERSONEL WHERE 1 = 0;

INSERT ALL
    WHEN UNVAN = 'UZMAN' THEN
        INTO PERSONEL_UZMAN VALUES(PERSONEL_ID, AD, SOYAD, MAAS, UNVAN)
    WHEN UNVAN IN ('MÜDÜR', 'GRUP MÜDÜRÜ') THEN
        INTO PERSONEL_YONETICI VALUES(PERSONEL_ID, AD, SOYAD, MAAS, UNVAN)
SELECT AD, SOYAD, PERSONEL_ID, MAAS, PRIM, UNVAN
FROM PERSONEL;

SELECT * FROM PERSONEL_UZMAN;
SELECT * FROM PERSONEL_YONETICI;

INSERT INTO PERSONEL_YONETICI
SELECT AD, SOYAD, PERSONEL_ID, MAAS, PRIM, UNVAN
FROM PERSONEL
WHERE UNVAN IN ('MÜDÜR','GRUP MÜDÜRÜ');

INSERT FIRST
    WHEN MAAS <= 3000 THEN
        INTO DUSUK_MAAS VALUES(PERSONEL_ID, AD, SOYAD, MAAS)
    WHEN MAAS BETWEEN 3000 AND 6000 THEN
        INTO ORTA_MAAS VALUES(PERSONEL_ID, AD, SOYAD, MAAS)
    ELSE
        INTO YUKSEK_MAAS VALUES (PERSONEL_ID, AD, SOYAD, MAAS)
SELECT PERSONEL_ID AD, SOYAD, MAAS
FROM PERSONEL;

CREATE TABLE BILGILER
(
    PERSONEL_ID NUMBER,
    KOD INTEGER,
    ACIKLAMA VARCHAR2(100),
    DEGER VARCHAR2(100)
);

INSERT ALL
    INTO BILGILER VALUES(PERSONEL_ID, 1, 'Adı-Soyadı', ad||' '||Soyad)
    INTO BILGILER VALUES(PERSONEL_ID, 2, 'Unvan', unvan)
    INTO BILGILER VALUES(PERSONEL_ID, 3, 'Maaş', toChar(maas))
    INTO BILGILER VALUES(PERSONEL_ID, 4, 'Semt', semt)
    INTO BILGILER VALUES(PERSONEL_ID, 5, 'Giriş Tarihi',
        TO_CHAR(GIRIS_TARIHI, 'DD.MM.YYYY'))
SELECT * FROM PERSONEL;

INSERT ALL
    INTO BILGILER (PERSONEL_ID, KOD, ACIKLAMA, DEGER)
    VALUES (PERSONEL_ID, 1, 'Adı-Soyadı', ad || ' ' || Soyad)
    INTO BILGILER (PERSONEL_ID, KOD, ACIKLAMA, DEGER)
    VALUES (PERSONEL_ID, 2, 'Unvan', unvan)
    INTO BILGILER (PERSONEL_ID, KOD, ACIKLAMA, DEGER)
    VALUES (PERSONEL_ID, 3, 'Maaş', TO_CHAR(maas))
    INTO BILGILER (PERSONEL_ID, KOD, ACIKLAMA, DEGER)
    VALUES (PERSONEL_ID, 4, 'Semt', semt)
    INTO BILGILER (PERSONEL_ID, KOD, ACIKLAMA, DEGER)
    VALUES (PERSONEL_ID, 5, 'Giriş Tarihi', TO_CHAR(GIRIS_TARIHI, 'DD.MM.YYYY'))
SELECT PERSONEL_ID, ad, Soyad, unvan, maas, semt, GIRIS_TARIHI FROM PERSONEL;

CREATE TABLE BILGILER
(
    PERSONEL_ID NUMBER,
    KOD INTEGER,
    ACIKLAMA VARCHAR2(100),
    DEGER VARCHAR2(100)
);

CREATE TABLE PRS1 AS
SELECT PERSONEL_ID, AD, SOYAD, MAAS, UNVAN
FROM PERSONEL WHERE UNVAN IN('MÜHENDİS', 'UZMAN');

CREATE TABLE PRS2 AS
SELECT PERSONEL_ID, AD, SOYAD, MAAS, UNVAN
FROM PERSONEL WHERE UNVAN IN ('MÜHENDİS','UZMAN','MÜDÜR');

UPDATE PRS2 SET MAAS = MAAS * 1.05 WHERE UNVAN != 'MÜDÜR';

MERGE INTO PRS1 P1
USING PRS2 P2
    ON (P1.PERSONEL_ID = P2.PERSONEL_ID)
WHEN MATCHED THEN
    UPDATE SET P1.MAAS = P2.MAAS
    DELETE WHERE MAAS > 5000
WHEN NOT MATCHED THEN
    INSERT (PERSONEL_ID, AD, SOYAD, MAAS, UNVAN)
    VALUES (P2.PERSONEL_ID, P2.AD, P2.SOYAD, P2.MAAS, P2.UNVAN);
    
SELECT * FROM PRS1;
*/















