ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER NORTHWIND IDENTIFIED BY "dbhunter"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO NORTHWIND;
  ALTER USER NORTHWIND DEFAULT ROLE ALL;
  ALTER USER NORTHWIND QUOTA UNLIMITED ON USERS;
  GRANT CREATE ROLE TO NORTHWIND;
  GRANT CREATE USER TO NORTHWIND;
  GRANT CREATE SESSION TO NORTHWIND;