ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER EGITIM IDENTIFIED BY "dbhunter"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT DBA TO EGITIM;
  ALTER USER EGITIM DEFAULT ROLE ALL;
  ALTER USER EGITIM QUOTA UNLIMITED ON USERS;
  GRANT CREATE ROLE TO EGITIM;
  GRANT CREATE USER TO EGITIM;
  GRANT CREATE SESSION TO EGITIM;
