CREATE TABLE BASKET_A
(
    ID_A INT PRIMARY KEY,
    FRUIT_A VARCHAR (50) NOT NULL
);

CREATE TABLE BASKET_B
(
    ID_B INT PRIMARY KEY,
    FRUIT_B VARCHAR (50) NOT NULL
);

CREATE TABLE BASKET_C
(
    ID_C INT PRIMARY KEY,
    FRUIT_C VARCHAR (50) NOT NULL
);

CREATE TABLE CARS
(
    ID INTEGER PRIMARY KEY,
    BRAND VARCHAR (100) NOT NULL,
    PRICE INTEGER NOT NULL,
    DISCOUNT INTEGER
);

CREATE TABLE CAR_TYPES
(
    ID INTEGER PRIMARY KEY,
    TYPE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE COLORS
(
    COLOR VARCHAR(50)
);

CREATE TABLE STUDENT
(
    ID INTEGER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CLASS_NO INTEGER DEFAULT 1,
    MARK INTEGER DEFAULT 0,
    GENDER VARCHAR2(6) DEFAULT 'Female',
    COURSE_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100)
); 

CREATE TABLE PRODUCT_SEGMENT (
    ID INT PRIMARY KEY,
    SEGMENT VARCHAR2(50) NOT NULL,
    DISCOUNT NUMERIC (4, 2)
);

CREATE TABLE PRODUCT(
    ID INT PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE,
    PRICE NUMERIC(10,2),
    NET_PRICE NUMERIC(10,2),
    SEGMENT_ID INT NOT NULL,
    FOREIGN KEY(SEGMENT_ID) REFERENCES PRODUCT_SEGMENT(ID)
);
